### ISSUE TITLE
Lambda Null Pointer Exception

### ISSUE THREAD

**Issue by tomott12345** [h2oai/dai-deployment-templates#190]
Was working with a prospect to test out AWS Lambda deployment. He was getting these errors. The problem was that his JSON file (test.json) was malformed. Need a more graceful way to fail in these cases. 

Error details:
java.lang.NullPointerException
        at ai.h2o.mojos.deploy.common.transform.RequestChecker.getProblemMessageOrNull(RequestChecker.java:52)
        at ai.h2o.mojos.deploy.common.transform.RequestChecker.verify(RequestChecker.java:25)
        at ai.h2o.mojos.deploy.aws.lambda.MojoScorer.score(MojoScorer.java:48)
        at ai.h2o.mojos.deploy.aws.lambda.ApiGatewayWrapper.handleRequest(ApiGatewayWrapper.java:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:263)
        at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180)
        at lambdainternal.EventHandlerLoader$2.c

**Comment by nkpng2k** [comment]
@tomott12345 thanks for providing trace... will look to this. cc @JHerna17 do you have maybe more time to look at this?
